 <?php
// this will get moved to an external php file in the future
$servername = "localhost";
$username = "dbsadmin";
$password = "dbspassadmin";
$dbname = "attempt1";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
echo "Connected successfully";


$sql = "SELECT region_id, region_name FROM region";
$result = $conn->query($sql);

mysqli_query($conn,"DELETE FROM region" );
 mysqli_query($conn,"INSERT INTO region(region_id, region_name) VALUES ('1','British Columbia')");
 mysqli_query($conn,"INSERT INTO region(region_id, region_name) VALUES ('2','Alberta')");
 mysqli_query($conn,"INSERT INTO region(region_id, region_name) VALUES ('3','Ontario')");

mysqli_query($conn,"DELETE FROM school" ); 
 mysqli_query($conn,"INSERT INTO school(school_id, school_name, region_id) VALUES ('1','UNBC','1')");
 mysqli_query($conn,"INSERT INTO school(school_id, school_name, region_id) VALUES ('2','UVIC','1')");
 mysqli_query($conn,"INSERT INTO school(school_id, school_name, region_id) VALUES ('3','UALB','2')");
 mysqli_query($conn,"INSERT INTO school(school_id, school_name, region_id) VALUES ('4','UCAL','2')");
 mysqli_query($conn,"INSERT INTO school(school_id, school_name, region_id) VALUES ('5','NAIT','2')");
 mysqli_query($conn,"INSERT INTO school(school_id, school_name, region_id) VALUES ('6','UONT','3')");
 
mysqli_query($conn,"DELETE FROM team" );
 mysqli_query($conn,"INSERT INTO team(team_id, team_name, school_id, num_times_opp, num_times_gov) VALUES ('1','UnrealTeam','1','0','0')");
 mysqli_query($conn,"INSERT INTO team(team_id, team_name, school_id, num_times_opp, num_times_gov) VALUES ('2','NotRealTeam','2','0','0')");
 mysqli_query($conn,"INSERT INTO team(team_id, team_name, school_id, num_times_opp, num_times_gov) VALUES ('3','FictionTeam','3','0','0')");
 mysqli_query($conn,"INSERT INTO team(team_id, team_name, school_id, num_times_opp, num_times_gov) VALUES ('4','AnotherTeam','3','0','0')");
 mysqli_query($conn,"INSERT INTO team(team_id, team_name, school_id, num_times_opp, num_times_gov) VALUES ('5','OtherTEam','4','0','0')");
 mysqli_query($conn,"INSERT INTO team(team_id, team_name, school_id, num_times_opp, num_times_gov) VALUES ('6','YetAnother','5','0','0')");
 mysqli_query($conn,"INSERT INTO team(team_id, team_name, school_id, num_times_opp, num_times_gov) VALUES ('7','OneMoreTeam','6','0','0')");
 mysqli_query($conn,"INSERT INTO team(team_id, team_name, school_id, num_times_opp, num_times_gov) VALUES ('8','LastTeam','6','0','0')");

mysqli_query($conn,"DELETE FROM speaker" );
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('1','Adam','Surname','3','1','1')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('2','Isabelle','Surname','4','1','1')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('3','Belle','Surname','5','2','2')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('4','Jasmine','Surname','6','2','2')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('5','Calli','Surname','7','3','3')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('6','Ken','Surname','8','3','3')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('7','Dan','Surname','9','3','4')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('8','Leah','Surname','8','3','4')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('9','Edward','Surname','7','4','5')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('10','Matt','Surname','6','4','5')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('11','Frank','Surname','5','5','6')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('12','Nami','Surname','4','5','6')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('13','Greta','Surname','3','6','7')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('14','Oswald','Surname','3','6','7')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('15','Howard','Surname','4','6','8')");
 mysqli_query($conn,"INSERT INTO speaker(speaker_id, speaker_first_name,  speaker_last_name, rank, school_id, team_id) VALUES ('16','Surname','Surname','5','6','8')");

mysqli_query($conn,"DELETE FROM judge" );
 mysqli_query($conn,"INSERT INTO judge(judge_id, judge_first_name,  judge_last_name, rank, school_id) VALUES ('1','Judge','Reinhold','3','1')");
 mysqli_query($conn,"INSERT INTO judge(judge_id, judge_first_name,  judge_last_name, rank, school_id) VALUES ('2','Judge','Davis','6','1')");
 mysqli_query($conn,"INSERT INTO judge(judge_id, judge_first_name,  judge_last_name, rank, school_id) VALUES ('3','Judge','Wilbur','9','2')");
 mysqli_query($conn,"INSERT INTO judge(judge_id, judge_first_name,  judge_last_name, rank, school_id) VALUES ('4','Judge','Parker','8','3')");
 mysqli_query($conn,"INSERT INTO judge(judge_id, judge_first_name,  judge_last_name, rank, school_id) VALUES ('5','Judge','Dredd','5','4')");
 mysqli_query($conn,"INSERT INTO judge(judge_id, judge_first_name,  judge_last_name, rank, school_id) VALUES ('6','Judge','Bone','2','4')");
 mysqli_query($conn,"INSERT INTO judge(judge_id, judge_first_name,  judge_last_name, rank, school_id) VALUES ('7','Judge','Snyder','4','5')");
 mysqli_query($conn,"INSERT INTO judge(judge_id, judge_first_name,  judge_last_name, rank, school_id) VALUES ('8','Judge','Harm','6','6')");

mysqli_query($conn,"DELETE FROM room" );
 mysqli_query($conn,"INSERT INTO room(room_id, room_name, room_priority) VALUES ('1','8-150','2')");
 mysqli_query($conn,"INSERT INTO room(room_id, room_name, room_priority) VALUES ('2','8-152','4')");
 mysqli_query($conn,"INSERT INTO room(room_id, room_name, room_priority) VALUES ('3','8-157','6')");
 mysqli_query($conn,"INSERT INTO room(room_id, room_name, room_priority) VALUES ('4','8-181','8')");
 
mysqli_query($conn,"DELETE FROM scratches" ); 
 mysqli_query($conn,"INSERT INTO scratches(judge_id, speaker_id) VALUES ('1','1')");

mysqli_query($conn,"DELETE FROM pairing_preference" );
 mysqli_query($conn,"INSERT INTO pairing_preference(pp_id, pp_name, custom_bracket_size, reseed_pullout, matching_type, max_allowed_govt_assignments, random_room_assignment, bracket_type, same_school, same_region, pullup_only_once, previously_paired, pullout_type) VALUES ('1', 'preferencesName', '2', 'f', 'Random', '1', 't', 'Win-Loss / Points', 't', 't', 'f', 't', 'Top Pullup')");

mysqli_query($conn,"DELETE FROM round" ); 
 mysqli_query($conn,"INSERT INTO round(round_id, round_name, pp_id) VALUES ('1','Round 1','1')");
 mysqli_query($conn,"INSERT INTO round(round_id, round_name, pp_id) VALUES ('2','Round 2','1')");
 mysqli_query($conn,"INSERT INTO round(round_id, round_name, pp_id) VALUES ('3','Round 3','1')");

mysqli_query($conn,"DELETE FROM pairing" );
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, priority, round_id, room_id) VALUES ('1','2','1','1')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, priority, round_id, room_id) VALUES ('2','2','1','2')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, priority, round_id, room_id) VALUES ('3','2','1','3')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, priority, round_id, room_id) VALUES ('4','2','1','4')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, priority, round_id, room_id) VALUES ('5','4','2','1')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, priority, round_id, room_id) VALUES ('6','4','2','2')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, priority, round_id, room_id) VALUES ('7','6','3','4')");

mysqli_query($conn,"DELETE FROM pairing_team" );
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('1','1')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('1','2')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('2','3')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('2','4')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('3','5')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('3','6')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('4','7')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('4','8')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('5','1')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('5','4')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('6','5')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('6','8')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('7','1')");
 mysqli_query($conn,"INSERT INTO pairing(pairing_id, team_id) VALUES ('7','5')");
 
mysqli_query($conn,"DELETE FROM judge_pairing" );
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('1','1')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('1','2')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('2','3')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('2','4')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('3','5')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('3','6')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('4','7')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('4','8')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('5','1')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('5','2')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('5','3')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('6','4')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('6','5')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('6','6')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('7','6')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('7','7')");
 mysqli_query($conn,"INSERT INTO judge_pairing(pairing_id, judge_id) VALUES ('7','8')");

mysqli_query($conn,"DELETE FROM pairing_team" );
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('1','1')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('1','2')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('2','3')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('2','4')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('3','5')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('3','6')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('4','7')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('4','8')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('5','1')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('5','4')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('6','5')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('6','8')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('7','1')");
 mysqli_query($conn,"INSERT INTO pairing_team(pairing_id, team_id) VALUES ('7','5')");
 

mysqli_query($conn,"DELETE FROM ballot" );
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('1','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('2','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('3','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('4','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('5','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('6','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('7','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('8','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('9','3')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('10','3')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('11','3')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('12','3')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('13','4')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('14','4')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('15','4')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('16','4')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('17','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('18','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('19','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('20','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('21','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('22','1')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('23','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('24','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('25','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('26','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('27','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('28','2')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('29','4')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('30','4')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('31','4')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('32','4')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('33','4')");
 mysqli_query($conn,"INSERT INTO ballot(ballot_id, room_id) VALUES ('34','4')");
 
mysqli_query($conn,"DELETE FROM ballot_round" );
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('1','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('2','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('3','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('4','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('5','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('6','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('7','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('8','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('9','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('10','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('11','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('12','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('13','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('14','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('15','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('16','1')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('17','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('18','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('19','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('20','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('21','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('22','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('23','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('24','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('25','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('26','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('27','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('28','2')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('29','3')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('30','3')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('31','3')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('32','3')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('33','3')");
 mysqli_query($conn,"INSERT INTO ballot_round(ballot_id, round_id) VALUES ('34','3')");

mysqli_query($conn,"DELETE FROM ballot_team" ); 
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('1','1')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('2','2')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('3','1')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('4','2')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('5','3')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('6','4')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('7','3')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('8','4')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('9','5')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('10','6')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('11','5')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('12','6')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('13','7')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('14','8')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('15','7')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('16','8')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('17','1')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('18','4')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('19','1')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('20','4')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('21','1')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('22','4')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('23','5')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('24','8')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('25','5')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('26','8')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('27','5')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('28','8')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('29','1')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('30','5')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('31','1')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('32','5')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('33','1')");
 mysqli_query($conn,"INSERT INTO ballot_team(ballot_id, team_id) VALUES ('34','5')");
 
mysqli_query($conn,"DELETE FROM ballot_speaker_scores");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('1','1','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('2','2','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('3','3','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('4','4','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('5','1','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('6','2','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('7','3','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('8','4','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('9','5','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('10','6','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('11','7','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('12','8','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('13','5','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('14','6','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('15','7','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('16','8','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('17','9','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('18','10','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('19','11','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('20','12','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('21','9','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('22','10','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('23','11','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('24','12','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('25','13','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('26','14','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('27','15','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('28','16','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('29','13','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('30','14','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('31','15','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('32','16','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('33','1','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('34','2','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('35','7','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('36','8','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('37','1','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('38','2','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('39','7','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('40','8','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('41','1','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('42','2','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('43','7','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('44','8','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('45','9','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('46','10','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('47','15','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('48','16','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('49','9','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('50','10','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('51','15','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('52','16','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('53','9','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('54','10','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('55','15','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('56','16','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('57','1','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('58','2','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('59','9','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('60','10','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('61','1','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('62','2','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('63','9','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('64','10','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('65','1','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('66','2','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('67','9','1','1','1','1','1','')");
 mysqli_query($conn,"INSERT INTO ballot_speaker_scores(ballot_id, speaker_id, `organization/structure`, `evidence/analysis`, `rebuttal/clash`, `delivery/etiquette`, `questioning/responding`, comments) VALUES ('68','10','1','1','1','1','1','')");
 
/*
 mysqli_query($conn,"DELETE FROM judge_ballot" ); 
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('1', '1', '1')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('1', '1', '2')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('1', '1', '3')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('1', '1', '4')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('2', '1', '5')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('2', '1', '6')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('2', '1', '7')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('2', '1', '8')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('3', '2', '9')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('3', '2', '10')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('3', '2', '11')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('3', '2', '12')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('4', '2', '13')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('4', '2', '14')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('4', '2', '15')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('4', '2', '16')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('5', '3', '17')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('5', '3', '18')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('5', '3', '19')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('5', '3', '20')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '3', '21')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '3', '22')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '3', '23')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '3', '24')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('7', '4', '25')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('7', '4', '26')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('7', '4', '27')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('7', '4', '28')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('8', '4', '29')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('8', '4', '30')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('8', '4', '31')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('8', '4', '32')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('1', '5', '33')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('1', '5', '34')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('1', '5', '35')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('1', '5', '36')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('2', '5', '37')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('2', '5', '38')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('2', '5', '39')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('2', '5', '40')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('3', '5', '41')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('3', '5', '42')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('3', '5', '43')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('3', '5', '44')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('4', '6', '45')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('4', '6', '46')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('4', '6', '47')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('4', '6', '48')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('5', '6', '49')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('5', '6', '50')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('5', '6', '51')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('5', '6', '52')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '6', '53')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '6', '54')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '6', '55')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '6', '56')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '7', '57')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '7', '58')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '7', '59')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('6', '7', '60')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('7', '7', '61')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('7', '7', '62')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('7', '7', '63')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('7', '7', '64')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('8', '7', '65')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('8', '7', '66')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('8', '7', '67')");
 mysqli_query($conn,"INSERT INTO judge_ballot(judge_id, pairing_id, ballot_id) VALUES ('8', '7', '68')");
*/ 
 //mysqli_query($conn,"INSERT INTO (,,) VALUES ('')");
 
 
 mysqli_close($conn);
?>