$(document).ready(function(){
	$("#registration").click(function(){
		$("#content").load("registration.php");
	});
});
$(document).ready(function(){
	$("#tournaments").click(function(){
		$("#content").load("tournaments.php");
	});
});
$(document).ready(function(){
	$("#results").click(function(){
		$("#content").load("results.php");
	});
});
$(document).ready(function(){
	$("#tools").click(function(){
		$("#content").load("tools.php");
	});
});
$(document).ready(function(){
	$("#logout").click(function(){
	});
});